version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - ecomnetwork

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - backend_staticfiles:/django-app/staticfiles
      - backend_media:/django-app/media
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - ecomnetwork

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run dev
    expose:
      - 5173
    # volumes:
    #   - frontend_build:/react-app/dist
    depends_on:
      - backend
    networks:
      - ecomnetwork
  
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - backend_staticfiles:/app/staticfiles
      - backend_media:/app/media
      # - frontend_build:/usr/share/nginx/html
    depends_on:
      - db
      - backend
      - frontend
    networks:
      - ecomnetwork

networks:
  ecomnetwork:
    name: ecomnetwork
    driver: bridge


volumes:
  postgres_data:
  backend_staticfiles:
  backend_media:
  # frontend_build:
